name: test_app_innowise
description: Weather forecast

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/launch_icon.webp"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
